coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 1%
        branches:
          - main
    patch:
      default:
        target: 80%
        threshold: 1%
ignore:
  - 'node_modules/*'
  - 'coverage/*'
  - '**/*.test.ts'
  - '**/*.test.tsx'
  - '**/__tests__/*'
